const fs = require("fs")
let c = fs.readFileSync("src/App.jsx", "utf8")
c = c.replace(/:  =/g, " =")
c = c.replace(/: =/g, " =")
fs.writeFileSync("src/App.jsx", c)
console.log("Fixed. Lines:", c.split("\n").length)
