const fs = require("fs")
let c = fs.readFileSync("src/App.jsx", "utf8")
c = c.replace(/:\[\]/g, "")
c = c.replace(/:  =/g, " =")
c = c.replace(/: =/g, " =")
c = c.replace(/Record</g, "")
c = c.replace(/>/g, "")
c = c.replace(/ as string/g, "")
c = c.replace(/ as number/g, "")
c = c.replace(/ as boolean/g, "")
c = c.replace(/: string, /g, ", ")
c = c.replace(/: string\)/g, ")")
c = c.replace(/: string; /g, "; ")
c = c.replace(/: string }/g, " }")
c = c.replace(/: number, /g, ", ")
c = c.replace(/: number\)/g, ")")
c = c.replace(/: boolean\)/g, ")")
c = c.replace(/\(, \)/g, "(userId, newPlan)")
c = c.replace(/\]\[\]/g, "]")
c = c.replace(/ as \{[^}]*\}/g, "")
fs.writeFileSync("src/App.jsx", c)
console.log("Fixed TS leftovers. Lines:", c.split("\n").length)
